name: Deploy to prod - patch
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump patch and push tag
      run: |
        git fetch -p
        VERSION=`git describe --abbrev=0 --tags`
        VERSION_BITS=(${VERSION//./ })
        MAJOR=${VERSION_BITS[0]}
        MINOR=${VERSION_BITS[1]}
        PATCH=${VERSION_BITS[2]}
        PATCH=$((PATCH+1))
        NEW_TAG="$MAJOR.$MINOR.$PATCH"
        echo "Updating $VERSION to $NEW_TAG"
        GIT_COMMIT=`git rev-parse HEAD`
        NEEDS_TAG=$(git describe --contains $GIT_COMMIT 2>/dev/null || echo need_tag)
        if [ $NEEDS_TAG == "need_tag" ]; then
          git tag $NEW_TAG
          echo "Tagged with $NEW_TAG"
          git push --tags
        else
          echo "Already a tag on this commit"
        fi

    - name: Set env
      run: |
        git fetch -p
        echo "release=$(git describe --tags  `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
    
    - name: Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release }}
        release_name: "Release ${{ env.release }}"
        draft: false
        prerelease: false
