name: Manual workflow - bump minor
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Merge main back to dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch --unshallow
        git checkout dev
        git pull
        git merge --no-ff main -m "Auto-merge main back to dev"
        git push

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
