name: Prod hot fix - bump patch
on:
  push:
    branches:
      - 'release_**'
      - '!main'
      - '!dev'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    -name: Set env
      run: echo "RELEASE_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Create pull-request release to dev
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                     
        destination_branch: "dev"
        pr_title: "Pulling $RELEASE_NAME into dev"
        pr_body: ":crown: *An automated PR*"                                 
        pr_allow_empty: true              
        github_token: ${{ secrets.GITHUB_TOKEN }}

