name: Manual workflow - bump patch
on:
  push:
    branches:
      - 'release_**'
      - '!main'
      - '!dev'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - name: Send greeting
      run: echo "Hello world"

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Merge release back to dev
      run: |
        release_branch=$(git branch | grep "release_")
        git fetch -p
        git checkout dev
        git pull
        git merge --no-ff $(echo "${release_branch:2}") -m "Auto-merge main back to dev"
        git push
