name: Manual workflow - bump minor
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Create pull-request main to dev
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "main"                           
        destination_branch: "dev"                      
        pr_title: "Pulling ${{ github.ref }} into dev" 
        pr_body: ":crown: *An automated PR*"                                           
        pr_allow_empty: true                              
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git config
      run: |
          git config --local user.email "madjid.djennane@outlook.fr"
          git config --local user.name "Madjid-Djennane"

    - name: Create release branch
      run: |
        VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        VERSION_BITS=(${VERSION//./ })
        MAJOR=${VERSION_BITS[0]}
        MINOR=${VERSION_BITS[1]}
        RELEASE_NAME="release_$MAJOR.$MINOR"
        git fetch -p
        git checkout main
        git checkout -b $(echo $RELEASE_NAME) main
        git push origin $(echo $RELEASE_NAME)

    - name: Set env
      run: echo "release=$(git describe --tags  `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Test
      run: echo "${{ env.release }}"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release }}
        release_name: ${{ env.release }}
        draft: false
        prerelease: false
