name: Manual workflow - bump minor
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Set Git config
      run: |
          git config --local user.email "madjid.djennane@outlook.fr"
          git config --local user.name "Madjid-Djennane"

    - name: Merge main back to dev
      run: |
        git fetch -p
        git checkout dev
        git pull
        git merge --no-ff main -m "Auto-merge main back to dev"
        git push

    - name: Create release branch
      run: |
        git fetch -p
        git checkout main
        git checkout -b release_$(git describe --tags --abbrev=0) main
        git push origin release_$(git describe --tags --abbrev=0)
