name: Manual workflow - bump patch
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

    - name: Send greeting
      run: echo "Hello world"

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
