
name: Manual workflow - test
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

      - name: Set env
        run: |
          echo "release=$(git describe --tags  `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Test
        run: | 
          echo "${{ env.release }}"
